CREATE TABLE USUARIO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    EMAIL VARCHAR(500),
    SENHA VARCHAR(255), 
    TIPO ENUM('COMUM', 'PERSONAL', 'ADMIN') DEFAULT 'COMUM' NOT NULL
);

CREATE TABLE EXERCICIO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    AGRUPAMENTO VARCHAR(50) NOT NULL,
    NIVEL VARCHAR(30) NOT NULL,
    DESCRICAO TEXT,
    IMAGE VARCHAR(255),
    VIDEO VARCHAR(255)
);

CREATE TABLE LISTA(
    ID VARCHAR(36) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA VARCHAR(20) NOT NULL,
    DIA ENUM('SEGUNDA', 'TERÇA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO','DOMINGO') DEFAULT 'COMUM' NOT NULL
);

CREATE TABLE LISTA_EXERCICIO_ITEM (
    LISTA_ID VARCHAR(36) NOT NULL,
    EXERCICIO_ID VARCHAR(36) NOT NULL,
    PRIMARY KEY (LISTA_ID, EXERCICIO_ID),
    FOREIGN KEY (LISTA_ID) REFERENCES LISTA(ID),
    FOREIGN KEY (EXERCICIO_ID) REFERENCES EXERCICIO(ID)
);

CREATE TABLE PERSONAL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    CONTATO VARCHAR(20),
    ESPECIALIDADE VARCHAR(255),
    DESCRICAO TEXT,
    IMAGE VARCHAR(255),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);